// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqqqdsgxxjhxvcuskwck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxcXFkc2d4eGpoeHZjdXNrd2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODk3NTYsImV4cCI6MjA2NjY2NTc1Nn0.bVdp9PPp_OgfL4gL0uDwTmFWYwhAyle7ycHUgMfcd6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);